FLAGES = -Wall -Werror -Wextra
SRC = ex06/ft_strlen.c ex05/ft_putstr.c ex04/ft_ultimate_div_mod.c ex03/ft_div_mod.c  ex02/ft_swap.c ex01/ft_ultimate_ft.c  ex00/ft_ft.c  main.c ft_putchar.c 

OBJECTS = test

all:
	gcc $(FLAGES)  $(SRC)  -o $(OBJECTS)

clean:
	rm -rf $(OBJECTS)

