FLAGES = -Wall -Werror -Wextra
SRC =  main.c ft_putchar.c ex01/ft_print_alphabet.c ex01/ft_print_reverse_alphabet.c ex02/ft_print_numbers.c ex03/ft_is_negative.c ex04/ft_print_comb.c ex05/ft_print_comb2.c ex06/ft_putnbr.c ex07/ft_print_combn.c

OBJECTS = test

all:
	gcc $(FLAGES)  $(SRC)  -o $(OBJECTS)

clean:
	rm -rf $(OBJECTS)

